package com.example.cil.freya;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;

import org.json.JSONException;
import org.json.JSONObject;

import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.UUID;

/**
 * Created by cil on 2/18/16.
 */
public class CreateNewServiceEntry extends Activity implements View.OnClickListener, Spinner.OnItemSelectedListener
{
    EditText info;
    int projNumb, creatorNumb, systemNumb, componentNumb;
    String ServiceEntryFile = "ServiceEntryFile.txt";
    Button createButton, backButton;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.create_new_service_entry);

        Spinner project = (Spinner) findViewById(R.id.SEprojects);
        Spinner creator = (Spinner) findViewById(R.id.creator);
        Spinner system = (Spinner) findViewById(R.id.SEsystem);
        Spinner component = (Spinner) findViewById(R.id.SEcomponent);

        Modules.spinner(this, getInfo.projectNames, project);
        Modules.spinner(this, getInfo.people, creator);
        Modules.spinner(this, getInfo.systemNames, system);
        Modules.spinner(this, getInfo.componentNames, component);

        createButton = (Button) findViewById(R.id.newServiceButton);
        createButton.setOnClickListener(this);
        backButton = (Button) findViewById(R.id.backServiceButton);
        backButton.setOnClickListener(this);

        try {Modules.read(ServiceEntryFile, this);}
        catch (FileNotFoundException e) {e.printStackTrace();}
    }

    @Override
    public void onItemSelected(AdapterView<?> parent, View view, int position, long id)
    {
        switch (parent.getId())
        {
            case (R.id.SEprojects):
                if (position > 0)
                    projNumb = getInfo.projectNumber[position - 1];
                break;

            case (R.id.creator):
                if (position > 0)
                    creatorNumb = getInfo.peopleNumber [position - 1];
                break;

            case (R.id.SEsystem):
                if (position > 0)
                    systemNumb = getInfo.systemNumber[position - 1];
                break;

            case (R.id.SEcomponent):
                if (position > 0)
                    componentNumb = getInfo.componentNumber[position - 1];
                break;
        }
    }


    @Override
    public void onNothingSelected(AdapterView<?> parent)
    {
        //autogenerated
    }

    public void newServiceEntry() throws JSONException
    {
        //Create JSONObject here
        JSONObject JSON = createServiceEntryJSON();

        getInfo.complete.put("Service Entry", JSON);
    }

    @Override
    public void onClick(View v)
    {        Intent intent;
        switch (v.getId())
        {
            case (R.id.newServiceButton):
                try {newServiceEntry();} catch (JSONException e) {e.printStackTrace();}
                new CRUD.writeMessage().execute(getInfo.complete);
              /*  try
                {newServiceEntry();} catch (JSONException e) {e.printStackTrace();}
                intent = new Intent(this, CreateNew.class);
                startActivity(intent);
                try{
                    Modules.write(info, ServiceEntryFile, this);}
                catch(FileNotFoundException e){e.printStackTrace();}*/
                break;

            case (R.id.backServiceButton):
                intent = new Intent(this, CreateNewDocument.class);
                startActivity(intent);
                break;
        }

    }

    public JSONObject createServiceEntryJSON() throws JSONException
    {
        JSONObject jsonParam = new JSONObject();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS", Locale.US);
        String date = sdf.format(new Date());

        jsonParam.put("Unique Identifier", UUID.randomUUID().toString());

        info = (EditText) findViewById(R.id.SEname);
        jsonParam.put("Name", info.getText().toString());

        jsonParam.put("Date", date);

        info = (EditText) findViewById(R.id.SEnotes);
        jsonParam.put("Notes", info.getText().toString());

        info = (EditText) findViewById(R.id.operation);
        jsonParam.put("Operations", info.getText().toString());

        jsonParam.put("Project", projNumb);

        jsonParam.put("Creator", creatorNumb);

        jsonParam.put("System", systemNumb);

        jsonParam.put("Component", componentNumb);

        jsonParam.put("Modification Date", date);

        jsonParam.put("Creation Date", date);

        //needs photo info
        jsonParam.put("Photo", null);

        return jsonParam;
    }


}
