package com.example.cil.freya;

import android.app.Activity;
import android.content.Intent;
import android.content.res.Configuration;
import android.os.Bundle;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.view.MenuItem;
import android.view.View;
import android.widget.AdapterView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ListView;
import android.widget.Spinner;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.FileNotFoundException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.UUID;

/**
 * Created by cil on 11/10/15.
 */
public class CreateNewProject extends MainActivity implements View.OnClickListener, Spinner.OnItemSelectedListener
{
    static String projectsURL = MainActivity.mainURL + MainActivity.edgeURL;
    Spinner prininvest;
    Button createButton;
    static JSONObject complete = new JSONObject();
    String ProjectFile = "ProjectFile.txt";
    private EditText txtEditor;
    int inNumb;
    EditText info = null;

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.create_new_project);
        createButton = (Button) findViewById(R.id.newProjectButton);
        createButton.setOnClickListener(this);
        prininvest = (Spinner) findViewById(R.id.prininvest);

        txtEditor = (EditText) findViewById(R.id.manager);
        try{
            Modules.read(ProjectFile, this);}
        catch(FileNotFoundException e){e.printStackTrace();}

        Modules.spinner (this, getInfo.peopleNames, prininvest);

        mDrawerToggle = new ActionBarDrawerToggle(
                MainActivity.this,                  /* host Activity */
                mDrawerLayout,         /* DrawerLayout object */
                  /* nav drawer icon to replace 'Up' caret */
                R.string.create,  /* "open drawer" description */
                R.string.create /* "close drawer" description */
        ) {

            /** Called when a drawer has settled in a completely closed state. */
            public void onDrawerClosed(View view) {
                super.onDrawerClosed(view);
                getActionBar().setTitle("close drawer");
            }

            /** Called when a drawer has settled in a completely open state. */
            public void onDrawerOpened(View drawerView) {
                super.onDrawerOpened(drawerView);
                getActionBar().setTitle("open drawer");
            }
        };

        // Set the drawer toggle as the DrawerListener
        mDrawerLayout.setDrawerListener(mDrawerToggle);

        getActionBar().setDisplayHomeAsUpEnabled(true);
        getActionBar().setHomeButtonEnabled(true);
        addDrawerItems();


    }
    public void onClick(View v)
    {
        switch (v.getId())
        {
            case (R.id.newProjectButton):
                try
                {newProject();} catch (JSONException e)
                {e.printStackTrace();}
                Intent intent = new Intent(this, CreateNewSite.class);
                startActivity(intent);
                try{
                    Modules.write(info, ProjectFile, this);}
                catch(FileNotFoundException e){e.printStackTrace();}
                break;
        }
    }

    @Override
    public void onItemSelected (AdapterView<?> parent, View view, int position, long id)
    {
        if (position > 0)
            inNumb = getInfo.peopleNumber[position-1];
    }

    @Override
    public void onNothingSelected(AdapterView<?> parent)
    {
        //autogenerated, do nothing
    }

    public void newProject() throws JSONException
    {

        //Create JSONObject here
        JSONObject JSON = createProjectJSON();

        JSONArray project = new JSONArray();
        project.put(JSON);

        complete.put("Project", project);
    }

    public JSONObject createProjectJSON() throws JSONException
    {
        JSONObject jsonParam = new JSONObject();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS", Locale.US);
        String date = sdf.format(new Date());

        info = (EditText) findViewById(R.id.institutionName);
        jsonParam.put("Institution Name", info.getText().toString());

        info = (EditText) findViewById(R.id.grant);
        jsonParam.put("Grant Number String", info.getText().toString());

        jsonParam.put("Unique Identifier", UUID.randomUUID().toString());

        info = (EditText) findViewById(R.id.manager);
        jsonParam.put("Name", info.getText().toString());


        jsonParam.put("Principal Investigator",inNumb);

        info = (EditText) findViewById(R.id.funding);
        jsonParam.put("Original Funding Agency", info.getText().toString());

        jsonParam.put("Modification Date", date);

        jsonParam.put("Creation Date", date);


        jsonParam.put("Started Date", date);

        return jsonParam;
    }

    @Override
    protected void onPostCreate(Bundle savedInstanceState) {
        super.onPostCreate(savedInstanceState);
        // Sync the toggle state after onRestoreInstanceState has occurred.
        mDrawerToggle.syncState();
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);
        mDrawerToggle.onConfigurationChanged(newConfig);
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Pass the event to ActionBarDrawerToggle, if it returns
        // true, then it has handled the app icon touch event
        if (mDrawerToggle.onOptionsItemSelected(item)) {
            return true;
        }
        // Handle your other action bar items...

        return super.onOptionsItemSelected(item);
    }

}