package com.example.cil.freya;

import android.app.Activity;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.ArrayAdapter;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Spinner;
import android.widget.Toast;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.UUID;

/**
 * Created by cil on 11/10/15.
 */
public class CreateNewProject extends Activity implements View.OnClickListener, Spinner.OnItemSelectedListener
{
    static String projectsURL = MainActivity.mainURL + MainActivity.edgeURL;
    Spinner prininvest;
    Button createButton;
    JSONArray edge;
    static JSONObject complete = new JSONObject();

    @Override
    protected void onCreate(Bundle savedInstanceState)
    {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.create_new_project);
        createButton = (Button) findViewById(R.id.post);
        createButton.setOnClickListener(this);
        prininvest = (Spinner) findViewById(R.id.prininvest);
        try
        {
            ArrayAdapter<String> spinAdapter = new ArrayAdapter<String>(this, android.R.layout.simple_spinner_item, MainActivity.investigators);
            spinAdapter.setDropDownViewResource(android.R.layout.simple_spinner_dropdown_item);
            prininvest.setAdapter(spinAdapter);
            prininvest.setOnItemSelectedListener(this);
        }catch (NullPointerException e){
            Toast.makeText(this, "Unable to populate People. Sync before trying again.", Toast.LENGTH_LONG).show();
            e.printStackTrace();
        }
    }
    public void onClick(View v)
    {
        switch (v.getId())
        {
            case (R.id.post):
                try
                {newProject();} catch (JSONException e)
                {e.printStackTrace();}
                Intent intent = new Intent(this, CreateNewSite.class);
                startActivity(intent);
                // Toast.makeText(CreateNewProject.this, "Post Successful", Toast.LENGTH_LONG).show();
                break;
        }
    }

    @Override
    public void onItemSelected (AdapterView<?> parent, View view, int position, long id)
    {
        Toast.makeText(parent.getContext(),
                "OnItemSelectedListener : " + parent.getItemAtPosition(position).toString(),
                Toast.LENGTH_SHORT).show();
    }

    @Override
    public void onNothingSelected(AdapterView<?> parent)
    {
        //autogenerated, do nothing
    }

    public void newProject() throws JSONException
    {

                //Create JSONObject here
                JSONObject JSON = createProjectJSON();

                JSONArray between = new JSONArray();
                between.put(JSON);

                JSONObject attrs = new JSONObject();
                attrs.put("Attrs", between);

                JSONArray project = new JSONArray();
                project.put(attrs);

                complete.put("Project", project);

          // edge = MainActivity.createEdge(complete);
}

        public JSONObject createProjectJSON() throws JSONException
        {
            JSONObject jsonParam = new JSONObject();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSS", Locale.US);
            String date = sdf.format(new Date());
            jsonParam.put("Create Date", date);
            EditText info = (EditText) findViewById(R.id.grant);
            jsonParam.put("Grant Number String", info.getText().toString());
            info = (EditText) findViewById(R.id.institutionName);
            jsonParam.put("Institution Name", info.getText().toString());
            jsonParam.put("Modification Date", date);
            info = (EditText) findViewById(R.id.projName);
            jsonParam.put("Name", info.getText().toString());
            info = (EditText) findViewById(R.id.funding);
            jsonParam.put("Original Funding Agency", info.getText().toString());
           // info = (EditText) findViewById(R.id.prininvest);
           // Integer investigator = Integer.parseInt(info.getText().toString());
            jsonParam.put("Principal Investigator", 1);
            jsonParam.put("Started Date", date);
            jsonParam.put("Unique Identifier", UUID.randomUUID().toString());
            return jsonParam;
        }
}
